# Generated by Django 3.2 on 2023-02-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dados_semanal', '0004_alter_semanal_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanal',
            name='estoque',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='semanal',
            name='projecao_m0',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='semanal',
            name='real',
            field=models.FloatField(default=0, null=True),
        ),
    ]
