# Generated by Django 3.2 on 2023-02-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dados_semanal', '0002_auto_20230207_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanal',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
