# Generated by Django 3.2 on 2023-02-10 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_dados_semanal', '0003_semanal_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanal',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
